# Generated by Django 4.2.5 on 2026-01-22 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0002_deliberationmessage_is_conclusion_and_more'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField(help_text='Daily execution time (HH:MM)')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('proposals_reviewed', models.JSONField(default=list, help_text='List of proposal IDs reviewed')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Session summary statistics')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='meetings.boardmeeting')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='AgentOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.JSONField(help_text='Structured opinion data with analysis')),
                ('previous_opinion', models.JSONField(blank=True, help_text='Previous opinion for comparison', null=True)),
                ('recommendation', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_INFO', 'Request More Information')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0.0 - 1.0)')),
                ('requires_human_attention', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.proposal')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'agent', 'proposal')},
            },
        ),
    ]
