# Generated by Django 4.2.27 on 2026-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentopinion',
            name='opinion',
        ),
        migrations.RemoveField(
            model_name='agentopinion',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='agentopinion',
            name='analysis',
            field=models.TextField(blank=True, help_text='Detailed analysis of the proposal'),
        ),
        migrations.AddField(
            model_name='agentopinion',
            name='evidence',
            field=models.JSONField(blank=True, default=list, help_text='Supporting evidence and references'),
        ),
        migrations.AddField(
            model_name='agentopinion',
            name='improvements',
            field=models.JSONField(blank=True, default=dict, help_text='Proposed improvements or changes'),
        ),
        migrations.AddField(
            model_name='agentopinion',
            name='suggestions',
            field=models.JSONField(blank=True, default=list, help_text='List of suggestions for improvement'),
        ),
        migrations.AddField(
            model_name='agentopinion',
            name='vote',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('DISAPPROVE', 'Disapprove'), ('ABSTAIN', 'Abstain')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
