# Generated by Django 4.2.27 on 2026-01-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_deliberationmessage_is_conclusion_and_more'),
        ('agents', '0001_initial'),
        ('meetings', '0002_remove_agentopinion_opinion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingsession',
            name='proposals_reviewed',
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='total_rounds',
            field=models.IntegerField(default=0, help_text='Total discussion rounds (max 5)'),
        ),
        migrations.AlterField(
            model_name='meetingsession',
            name='summary',
            field=models.JSONField(blank=True, default=dict, help_text='Session summary with voting results'),
        ),
        migrations.CreateModel(
            name='DiscussionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(help_text='Round number (1-5)')),
                ('statement', models.TextField(help_text="Agent's statement or proposal")),
                ('evidence', models.JSONField(default=list, help_text='Supporting evidence and references')),
                ('suggestions', models.JSONField(default=list, help_text='Suggestions for improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('responds_to', models.ForeignKey(blank=True, help_text='Which round is this responding to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.discussionround')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ['round_number', 'created_at'],
                'unique_together': {('session', 'round_number', 'agent')},
            },
        ),
    ]
