# Generated by Django 4.2.5 on 2026-01-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connector_type', models.CharField(choices=[('MYSQL', 'MySQL'), ('POSTGRES', 'PostgreSQL'), ('REDIS', 'Redis'), ('KAFKA', 'Kafka'), ('MILVUS', 'Milvus'), ('S3', 'S3/Minio')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
