# Generated by Django 4.2.5 on 2026-01-21 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('deliberating', 'Deliberating'), ('voting', 'Voting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_ceo', 'Pending CEO'), ('executed', 'Executed')], default='deliberating', max_length=50)),
                ('risk_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('content', models.JSONField(default=dict)),
                ('proposer', models.CharField(blank=True, max_length=100, null=True)),
                ('impact_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliberationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(default='', max_length=100)),
                ('agent_domain', models.CharField(default='', max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='proposals.proposal')),
            ],
        ),
    ]
