# Generated by Django 4.2.5 on 2026-01-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberationmessage',
            name='is_conclusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliberationmessage',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
